#!/bin/sh
# https://github.com/adobe-fonts/source-code-pro/issues/17#issuecomment-102803992

FONT_HOME=~/.local/share/fonts

mkdir -p "$FONT_HOME/adobe-fonts/source-code-pro"
(git clone \
   --branch release \
   --depth 1 \
   'https://github.com/adobe-fonts/source-code-pro.git' \
   "$FONT_HOME/adobe-fonts/source-code-pro" && \
fc-cache -f -v "$FONT_HOME/adobe-fonts/source-code-pro")

# find "$FONT_HOME" -iname '*.ttf' -exec echo '{}' \;
